runtime: python312
service: default
entrypoint: uvicorn dashboard:app --host 0.0.0.0 --port $PORT

instance_class: F1
automatic_scaling:
  max_instances: 1
  min_instances: 0

env_variables:
  REDDIT_CLIENT_ID: "sm://projects/reddit-buyer-dashboard/secrets/REDDIT_CLIENT_ID/versions/latest"
  REDDIT_CLIENT_SECRET: "sm://projects/reddit-buyer-dashboard/secrets/REDDIT_CLIENT_SECRET/versions/latest"
  REDDIT_USERNAME: "sm://projects/reddit-buyer-dashboard/secrets/REDDIT_USERNAME/versions/latest"
  REDDIT_PASSWORD: "sm://projects/reddit-buyer-dashboard/secrets/REDDIT_PASSWORD/versions/latest"
  REDDIT_USER_AGENT: "RedditBuyerIntentBot/1.0"
  GEMINI_API_KEY: "sm://projects/reddit-buyer-dashboard/secrets/GEMINI_API_KEY/versions/latest"
  SECRET_KEY: "sm://projects/reddit-buyer-dashboard/secrets/SECRET_KEY/versions/latest"
  DATABASE_URL: "postgresql+psycopg2://postgres:password@/reddit_dashboard?host=/cloudsql/reddit-buyer-dashboard:us-central1:reddit-dashboard-db"
  GOOGLE_CLIENT_ID: "sm://projects/reddit-buyer-dashboard/secrets/GOOGLE_CLIENT_ID/versions/latest"
  GOOGLE_CLIENT_SECRET: "sm://projects/reddit-buyer-dashboard/secrets/GOOGLE_CLIENT_SECRET/versions/latest"
  REDDIT_OAUTH_CLIENT_ID: "sm://projects/reddit-buyer-dashboard/secrets/REDDIT_OAUTH_CLIENT_ID/versions/latest"
  REDDIT_OAUTH_CLIENT_SECRET: "sm://projects/reddit-buyer-dashboard/secrets/REDDIT_OAUTH_CLIENT_SECRET/versions/latest"

# Add Cloud SQL instance connection
beta_settings:
  cloud_sql_instances: reddit-buyer-dashboard:us-central1:reddit-dashboard-db 