runtime: python312
service: default
entrypoint: uvicorn dashboard:app --host 0.0.0.0 --port $PORT

instance_class: F1
automatic_scaling:
  max_instances: 1
  min_instances: 0

env_variables:
  REDDIT_CLIENT_ID: "your_client_id"
  REDDIT_CLIENT_SECRET: "your_client_secret"
  REDDIT_USERNAME: "your_username"
  REDDIT_PASSWORD: "your_password"
  REDDIT_USER_AGENT: "RedditBuyerIntentBot/1.0"
  GEMINI_API_KEY: "AIzaSyBX_4_GoOitrlS30Fa-wVscPkuovZ6bdN4"
  SECRET_KEY: "09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7"
  DATABASE_URL: "sqlite:///./reddit_dashboard.db"
  GOOGLE_CLIENT_ID: "your_google_client_id"
  GOOGLE_CLIENT_SECRET: "your_google_client_secret"
  REDDIT_OAUTH_CLIENT_ID: "your_reddit_oauth_client_id"
  REDDIT_OAUTH_CLIENT_SECRET: "your_reddit_oauth_client_secret" 