runtime: python312
service: default
entrypoint: uvicorn dashboard:app --host 0.0.0.0 --port $PORT

instance_class: F1
automatic_scaling:
  max_instances: 1
  min_instances: 0

env_variables:
  REDDIT_CLIENT_ID: "YOUR_REDDIT_CLIENT_ID"
  REDDIT_CLIENT_SECRET: "YOUR_REDDIT_CLIENT_SECRET"
  REDDIT_USERNAME: "YOUR_REDDIT_USERNAME"
  REDDIT_PASSWORD: "YOUR_REDDIT_PASSWORD"
  REDDIT_USER_AGENT: "RedditBuyerIntentBot/1.0"
  GEMINI_API_KEY: "YOUR_GEMINI_API_KEY"
  SECRET_KEY: "YOUR_SECRET_KEY"
  DATABASE_URL: "sqlite:///./reddit_dashboard.db"
  GOOGLE_CLIENT_ID: "YOUR_GOOGLE_CLIENT_ID"
  GOOGLE_CLIENT_SECRET: "YOUR_GOOGLE_CLIENT_SECRET"
  REDDIT_OAUTH_CLIENT_ID: "YOUR_REDDIT_OAUTH_CLIENT_ID"
  REDDIT_OAUTH_CLIENT_SECRET: "YOUR_REDDIT_OAUTH_CLIENT_SECRET" 