runtime: python312
service: default
entrypoint: uvicorn dashboard:app --host 0.0.0.0 --port $PORT

instance_class: F1
automatic_scaling:
  max_instances: 1
  min_instances: 0

env_variables:
  REDDIT_CLIENT_ID: "5vx2u8kIdz8g5jjKTO2-Bg"
  REDDIT_CLIENT_SECRET: "ODujtHMmrRq4L6wrD6JK5_wRPmdlUQ"
  REDDIT_USERNAME: "nnnnngup"
  REDDIT_PASSWORD: "Pats3560"
  REDDIT_USER_AGENT: "RedditBuyerIntentBot/1.0"
  GEMINI_API_KEY: "AIzaSyBX_4_GoOitrlS30Fa-wVscPkuovZ6bdN4"
  SECRET_KEY: "09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7"
  DATABASE_URL: "postgresql+psycopg2://postgres:Reddit2024DB!@/reddit_dashboard?host=/cloudsql/reddit-buyer-dashboard:us-central1:reddit-dashboard-db"
  GOOGLE_CLIENT_ID: "318411767010-bouqo4p3j3sa2pmtl002abmno1dn9ce9.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "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"
  REDDIT_OAUTH_CLIENT_ID: "0ONs3bv8rYssfbJ881JYZQ"
  REDDIT_OAUTH_CLIENT_SECRET: "qebjoV2DtR5zrKZb9vbjP8F14i_YpA"

# Add Cloud SQL instance connection
beta_settings:
  cloud_sql_instances: reddit-buyer-dashboard:us-central1:reddit-dashboard-db 